### Exercice 1

Remplir un tableau de n entiers avec 2<=n<=20

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [6]:
import numpy as np
n=5
T=np.zeros(n)
def Remplir(T,n):
    for i in range(n):
        T[i]=int(input(f'Donner le contenu de la case N°{i}'))
    return T
print(Remplir(T,n))

Donner le contenu de la case N°0 3
Donner le contenu de la case N°1 6
Donner le contenu de la case N°2 2
Donner le contenu de la case N°3 3
Donner le contenu de la case N°4 3


[3. 6. 2. 3. 3.]


### Exercice 2

Ecrivez un programme NumPy pour créer un tableau de tous les entiers pairs de 30 à 70

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [8]:
import numpy as np
T=np.arange(30,70,2)
print(T)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


### Exercice 3

Ecrivez un programme NumPy pour créer un tableau avec des valeurs comprises entre 15 et 55 et imprimez toutes les valeurs sauf la première et la dernière

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [9]:
import numpy as np
T=np.arange(15,55)
print(T[1:55])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


### Exercice 4

La somme des éléments d'un tableau

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [10]:
import numpy as np
T=np.arange(0,20)
print(sum(T))

190


### Exercice 5

Le plus petit des éléments d'un tableau

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [13]:
import numpy as np
T=np.random.randint(10,size=10)
print(np.min(T))

0


### Exercice 6

Le plus grand des éléments d'un tableau

<h4 style="color:green"> Python</h4>

In [14]:
import numpy as np
T=np.random.randint(10,size=10)
print(np.max(T))

8


### Exercice 7

La moyenne des éléments d'un tableau

<h4 style="color:green"> Python</h4>

In [4]:
import numpy as np
t=np.random.randint(10, size=20)
m=np.mean(t)
print(t)
print(m)

[1 7 6 5 0 1 6 4 1 3 7 5 0 6 7 6 1 0 9 2]
3.85


### Exercice 8

La mediane des éléments d'un tableau

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [2]:
import numpy as np
t=np.random.randint(10, size=10)
print(t)
print(np.median(t))

[8 2 3 4 5 0 8 8 9 0]
4.5


### Exercice 9

Inverser l'ordre des éléments d'un tableau

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [12]:
import numpy as np
t=np.random.randint(10, size=10)
print(t)
print(np.flip(t))

[7 2 1 6 1 7 8 2 9 8]
[8 9 2 8 7 1 6 1 2 7]


### Exercice 10

Ecrivez un programme NumPy pour tester si aucun des éléments d'un tableau donné n'est nul

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [14]:
import numpy as np
#t=np.random.randint(10, size=10)
t=np.ones(10)
print(t)
print(np.all(t))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
True


### Exercice 11

Écrivez un programme NumPy pour tester si un des éléments d'un tableau donné est différent de zéro

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

### Exercice 12

Ecrivez un programme NumPy pour tester si deux tableaux sont égaux élément par élément

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [18]:
import numpy as np
#t1=np.random.randint(10, size=10)
#t2=np.random.randint(10, size=10)
t1=[6,5,6,4,9,5]
t2=[6,5,8,4,9,5]
print(t1)
print(t2)
print(np.allclose(t1,t2))

[6, 5, 6, 4, 9, 5]
[6, 5, 8, 4, 9, 5]
False


### Exercice 13

Ecrivez un programme NumPy pour créer une comparaison de deux tableaux donnés, retourne vrai si les deux tableaux contiennent les mêmes valeurs mêmes dans des indices différents et faux sinon

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

### Exercice 14

Ecrivez un programme NumPy pour créer un tableau de 10 zéros, 10 uns, 10 cinq

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

### Exercice 15

Ecrivez un programme NumPy pour créer un tableau de tous les entiers pairs de 30 à 70

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

### Exercice 16

Ecrivez un programme NumPy pour créer un tableau avec des valeurs comprises entre 15 et 55 et imprimez toutes les valeurs sauf la première et la dernière

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>