### Exercice 1

Remplir un tableau de n entiers avec 2<=n<=20

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [6]:
import numpy as np
n=5
T=np.zeros(n)
def Remplir(T,n):
    for i in range(n):
        T[i]=int(input(f'Donner le contenu de la case N°{i}'))
    return T
print(Remplir(T,n))

Donner le contenu de la case N°0 3
Donner le contenu de la case N°1 6
Donner le contenu de la case N°2 2
Donner le contenu de la case N°3 3
Donner le contenu de la case N°4 3


[3. 6. 2. 3. 3.]


### Exercice 2

Ecrivez un programme NumPy pour créer un tableau de tous les entiers pairs de 30 à 70

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [8]:
import numpy as np
T=np.arange(30,70,2)
print(T)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


### Exercice 3

Ecrivez un programme NumPy pour créer un tableau avec des valeurs comprises entre 15 et 55 et imprimez toutes les valeurs sauf la première et la dernière

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [9]:
import numpy as np
T=np.arange(15,55)
print(T[1:55])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


### Exercice 4

La somme des éléments d'un tableau

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [10]:
import numpy as np
T=np.arange(0,20)
print(sum(T))

190


### Exercice 5

Le plus petit des éléments d'un tableau

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [13]:
import numpy as np
T=np.random.randint(10,size=10)
print(np.min(T))

0


### Exercice 6

Le plus grand des éléments d'un tableau

<h4 style="color:green"> Python</h4>

In [14]:
import numpy as np
T=np.random.randint(10,size=10)
print(np.max(T))

8


### Exercice 7

La moyenne des éléments d'un tableau

<h4 style="color:green"> Python</h4>

In [15]:
import numpy as np
T=np.random.randint(10,size=19)
print(np.mean(T))

4.578947368421052


### Exercice 8

La mediane des éléments d'un tableau

<h4 style="color:green"> Algorithme</h4>

<h4 style="color:green"> Python</h4>

In [26]:
import numpy as np
T=np.random.randint(10,size=10)
print(T)
print(np.median(T))

[6 8 7 0 6 4 4 0 6 6]
6.0


### Exercice 9

Inverser l'ordre des éléments d'un tableau

In [15]:
import numpy as np
x=np.random.randint(10,size=10)
print(x)
print(np.flip(x))

[1 6 4 3 3 8 1 7 6 3]
[3 6 7 1 8 3 3 4 6 1]


### Exercice 10

Ecrivez un programme NumPy pour tester si aucun des éléments d'un tableau donné n'est nul

In [71]:
import numpy as np
x=np.random.randint(10,size=10)
print(x)
print(np.all(x))

[0 2 0 2 5 1 0 6 8 4]
[0 0 0 1 2 2 4 5 6 8]
False


### Exercice 11

Écrivez un programme NumPy pour tester si un des éléments d'un tableau donné est différent de zéro

In [24]:
import numpy as np
#x=np.random.randint(10,size=10)
x=np.zeros(10)
print(x)
print(np.any(x))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
False


### Exercice 12

Ecrivez un programme NumPy pour tester si deux tableaux sont égaux élément par élément

In [72]:
import numpy as np
#x1=np.random.randint(10,size=10)
x1=np.ones(10)
x2=np.ones(10)
print(np.allclose(x1,x2))

True


### Exercice 13

Ecrivez un programme NumPy pour créer une comparaison de deux tableaux donnés, retourne vrai si les deux tableaux contiennent les mêmes valeurs mêmes dans des indices différents et faux sinon

In [48]:
import numpy as np
def verif(t1,t2):
    i=0
    while t1[i] in t2 and i<len(t2)-1:
        i=i+1
    return t1[i] in t2
#t1=np.random.randint(10,size=10)
#t2=np.random.randint(10,size=10)
t1=[1,0,3,4,5,7]
t2=[7,5,4,3,0,1]
print(verif(t1,t2)and verif(t2,t1))

True


### Exercice 14

Ecrivez un programme NumPy pour créer un tableau de 10 zéros, 10 uns, 10 cinq

In [63]:
import numpy as np
t1=np.zeros(10, dtype=int)
t2=np.ones(10, dtype=int)
t3=np.full(10, 5)
t=np.concatenate((t1,t2,t3),axis=None)
print(t)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


### Exercice 15

Ecrivez un programme NumPy pour créer un tableau de tous les entiers pairs de 30 à 70

In [67]:
import numpy as np
t=np.arange(30, 71,2)
print(t)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


### Exercice 16

Ecrivez un programme NumPy pour créer un tableau avec des valeurs comprises entre 15 et 55 et imprimez toutes les valeurs sauf la première et la dernière

In [68]:
import numpy as np
t=np.arange(15,56)
print(t)
print(t[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
