<h1 style="color:purple; text-align:center">Tableaux à deux dimensions</h1>

<p style="font-size:30px">Un tableau à deux dimensions (<mark>Matrice</mark>) A est à interpréter comme un tableau (uni-dimensionnel / <mark>Vecteur</mark>) de dimension L dont chaque composante est un tableau (uni-dimensionnel) de dimension C.
</p>
<p style="font-size:30px">
    On appelle <mark>L</mark> le nombre de lignes du tableau et <mark>C</mark> le nombre de colonnes du tableau. L et C sont alors les deux dimensions du tableau. Un tableau à deux dimensions contient donc <mark>L*C</mark> composantes.
</p>

<table style="text-align:center">
    <tr>
    <td></td>
    <td></td>
	<td style="color:red;">-8</td>
	<td style="color:red;">-7</td>
	<td style="color:red;">-6</td>
	<td style="color:red;">-5</td>
	<td style="color:red;">-4</td>
	<td style="color:red;">-3</td>
	<td style="color:red;">-2</td>
	<td style="color:red;">-1</td>
</tr>
<tr>
    <td></td>
    <td></td>
	<td>0</td>
	<td>1</td>
	<td>2</td>
	<td>3</td>
	<td>4</td>
	<td>5</td>
	<td>6</td>
	<td>7</td>
</tr>
<tr>
    <td style="color:red;">-4</td>
    <td>0</td>
	<td style="border:solid">20</td>
	<td style="border:solid">25</td>
	<td style="border:solid">-5</td>
	<td style="border:solid">10</td>
	<td style="border:solid">10</td>
	<td style="border:solid">-52</td>
	<td style="border:solid">14</td>
	<td style="border:solid">3</td>
</tr>
 <tr>
    <td style="color:red;">-3</td>
    <td>1</td>
	<td style="border:solid">25</td>
	<td style="border:solid">12</td>
	<td style="border:solid">-9</td>
	<td style="border:solid">-10</td>
	<td style="border:solid">8</td>
	<td style="border:solid">36</td>
	<td style="border:solid">10</td>
	<td style="border:solid">48</td>
</tr>
    <tr>
    <td style="color:red;">-2</td>
    <td>2</td>
	<td style="border:solid">37</td>
	<td style="border:solid">20</td>
	<td style="border:solid">55</td>
	<td style="border:solid">-24</td>
	<td style="border:solid">56</td>
	<td style="border:solid">-59</td>
	<td style="border:solid">34</td>
	<td style="border:solid">30</td>
</tr>
    <tr>
    <td style="color:red;">-1</td>
    <td>3</td>
	<td style="border:solid">-19</td>
	<td style="border:solid">65</td>
	<td style="border:solid">18</td>
	<td style="border:solid">44</td>
	<td style="border:solid">8</td>
	<td style="border:solid">67</td>
	<td style="border:solid">17</td>
	<td style="border:solid">93</td>
</tr>
</table>
 <p style="color:red; text-align:center">Tableau de 4 lignes et 8 colonnes</p>

<p style="font-size:30px">On dit qu'un tableau à deux dimensions est <mark>carré</mark>, si L est égal à C.</p>
<p style="font-size:30px">
En faisant le rapprochement avec les mathématiques, on peut dire que "A est un vecteur de L vecteurs de dimension C", ou mieux:
</p>
<p style="font-size:30px">
"A est une matrice de dimensions L et C".
</p>


<h2 style="color:red">Déclaration Algorithmique</h2>

<table style="text-align:center">
<tr>
    <td colspan=2 style="font-size:30px">Tableau de Déclaration des Objets(T.D.O)</td>
</tr>
<tr>
    <td style="border:solid; font-size:30px">Objet</td>
	<td style="border:solid; font-size:30px">Type/Nature</td>
</tr>
<tr>
    <td style="border:solid; font-size:20px">Nom_Tableau M</td>
    <td style="border:solid; font-size:20px">Tableau de L lignes * C colonnes Type _élément


</tr>
</table>

<h2 style="color:blue">Création</h2>

Les tableaux (en anglais, array) peuvent être créés avec numpy.array(). On utilise des crochets pour délimiter les listes d’éléments dans les tableaux.

In [6]:
import numpy as np
m=np.array([[1,2,3,4,5,6],[5,7,9,6,5,4],[1,5,4,8,7,8]])
print(m)

[[1 2 3 4 5 6]
 [5 7 9 6 5 4]
 [1 5 4 8 7 8]]


<h3 style="color:orange">Création avec type</h3>

Au moment de la création d'un tableau on peut définir le type des éléments avec le paramètre "dtype"

In [8]:
import numpy as np
m1=np.array([[1,2,3,4,5,6],[5,7,9,6,5,4],[1,5,4,8,7,8]],dtype=int)
m2=np.array([[1,2,3,4,5,6],[5,7,9,6,5,4],[1,5,4,8,7,8]],dtype=float)
m3=np.array([[True,False,True],[True,False,True],[True,False,True]],dtype=bool)
print("Tableau d'entiers: ",m1)
print("Tableau de réels: ",m2)
print("Tableau de booléens: ",m3)

Tableau d'entiers:  [[1 2 3 4 5 6]
 [5 7 9 6 5 4]
 [1 5 4 8 7 8]]
Tableau de réels:  [[1. 2. 3. 4. 5. 6.]
 [5. 7. 9. 6. 5. 4.]
 [1. 5. 4. 8. 7. 8.]]
Tableau de booléens:  [[ True False  True]
 [ True False  True]
 [ True False  True]]


<h2 style="color:blue">Affichage</h2>

In [18]:
m=np.array([[1,2,3,4,5,6],[5,7,9,6,5,4],[1,5,4,8,7,8]],dtype=int)
print(m)

[[1 2 3 4 5 6]
 [5 7 9 6 5 4]
 [1 5 4 8 7 8]]


<h2 style="color:blue">Accès aux éléments d’un tableau</h2>

In [19]:
m=np.array([[1,2,3,4,5,6],[5,7,9,6,5,4],[1,5,4,8,7,8]],dtype=int)
print(m[0,0])
print(m[0][0])
print(m[-2][-1])

1
1
4


In [22]:
m=np.array([[1,2,3,4,5,6],[5,7,9,6,5,4],[1,5,4,8,7,8]],dtype=int)
m[-2][0]=55

In [23]:
print(m)

[[ 1  2  3  4  5  6]
 [55  7  9  6  5  4]
 [ 1  5  4  8  7  8]]


<h2 style="color:blue">Création directe</h2>

Il est souvent plus efficace, surtout pour les tableaux larges, de les créer directement. Numpy contient plusieurs fonctions pour cette tâche.

création d'un tableau de 10  lignes 8 colonnes <mark>zéros</mark>

In [24]:
v=np.zeros((10,8) ,dtype=int)
print(v)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


Création d'un tableau de 5 lignes 4 colonnes <mark>uns</mark>

In [25]:
v=np.ones((5,4), dtype=int)
print(v)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


création d'un tableau rempli d'une même <mark>valeur donnée</mark>

In [26]:
# création d'un tableau de 10 lignes 5 colonnes avec des valeurs, chacun égal à 5
v=np.full((10,5), 8)
print(v)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


Création d'un tableau rempli <mark>aléatoirement</mark>

In [34]:
# création d'un tableau de 3 lignes 5 colonnes avec des entiers aléatoire de l'intervalle [0,9]
t=np.random.randint(10, size=(3, 5))
print(t)

[[6 1 0 7 8]
 [4 1 9 6 5]
 [4 5 0 8 6]]


<h2 style="color:blue">Acces à une séquence (Slicing)</h2>

In [61]:
t=np.random.randint(10, size=(5, 5))
print(t)
# les éléments de la ligne 0 a la ligne 2 et de la colonne 1 à la colonne 4
x=t[0:2,1:4]
print(x)

[[0 6 2 3 6]
 [7 4 0 1 9]
 [0 8 7 0 8]
 [3 2 4 2 9]
 [3 6 3 1 0]]
[[6 2 3]
 [4 0 1]]
