<h1 style="color:purple; text-align:center">Tableaux à une dimension</h1>

Un tableau est un regroupement de valeurs portant le même nom de variable et repérées par un numéro. Il permet de ranger un nombre <mark>fini</mark> d’éléments de <mark>même type</mark> et selon une disposition bien définie. Le numéro qui permet de repérer chaque valeur s’appelle l’<mark>indice</mark>. 

<table style="text-align:center">
<tr>
    <td></td>
	<td>-8</td>
	<td>-7</td>
	<td>-6</td>
	<td>-5</td>
	<td>-4</td>
	<td>-3</td>
	<td>-2</td>
	<td>-1</td>
</tr>
<tr>
    <td>T</td>
	<td style="border:solid">20</td>
	<td style="border:solid">25</td>
	<td style="border:solid">-5</td>
	<td style="border:solid">10</td>
	<td style="border:solid">10</td>
	<td style="border:solid">-52</td>
	<td style="border:solid">14</td>
	<td style="border:solid">3</td>
</tr>
<tr>
    <td></td>
	<td>0</td>
	<td>1</td>
	<td>2</td>
	<td>3</td>
	<td>4</td>
	<td>5</td>
	<td>6</td>
	<td>7</td>
</tr>
</table>


<h2 style="color:red">Déclaration Algorithmique</h2>

<table style="text-align:center">
<tr>
    <td colspan=2 style="font-size:30px">Tableau de Déclaration des Objets(T.D.O)</td>
</tr>
<tr>
    <td style="border:solid; font-size:30px">Objet</td>
	<td style="border:solid; font-size:30px">Type/Nature</td>
</tr>
<tr>
    <td style="border:solid; font-size:20px">Nom_Tableau <br/> T</td>
    <td style="border:solid; font-size:20px">Tableau de &lt;<mark>nombre de cases</mark>&gt; &lt;<mark>type des éléments</mark>&gt;
    <br/> Tableau de 100 réels
    </td>

</tr>
</table>

<h2 style="color:red">En Python</h2>

La bibliothèque NumPy (http://www.numpy.org/) permet d’effectuer des calculs numériques avec Python. Elle introduit une gestion facilitée des tableaux de nombres.

Il faut au départ importer le package numpy avec l’instruction suivante :

In [5]:
import numpy as np

<h2 style="color:blue">Variables prédéfinies</h2>

In [6]:
print(np.pi)

3.141592653589793


<h2 style="color:blue">Création</h2>

Les tableaux (en anglais, array) peuvent être créés avec numpy.array(). On utilise des crochets pour délimiter les listes d’éléments dans les tableaux.

In [7]:
t=np.array([1,2,3,4,5,6])

<h3 style="color:orange">Création avec type</h3>

Au moment de la création d'un tableau on peut définir le type des éléments avec le paramètre "dtype"

In [8]:
t1=np.array([1,5,4,8], dtype=int)
t2=np.array([1,5,4,8], dtype=float)
t3=np.array([True,False,False,True], dtype=bool)
print("Tableau d'entiers: ",t1)
print("Tableau de réels: ",t2)
print("Tableau de booléens: ",t3)

Tableau d'entiers:  [1 5 4 8]
Tableau de réels:  [1. 5. 4. 8.]
Tableau de booléens:  [ True False False  True]


<h2 style="color:blue">Affichage</h2>

In [9]:
print(t)

[1 2 3 4 5 6]


<h2 style="color:blue">Accès aux éléments d’un tableau</h2>

In [10]:
print(t[0])

1


In [11]:
t[-2]=55

In [12]:
print(t)

[ 1  2  3  4 55  6]


<h2 style="color:blue">Création directe</h2>

Il est souvent plus efficace, surtout pour les tableaux larges, de les créer directement. Numpy contient plusieurs fonctions pour cette tâche.

création d'un tableau de 10 <mark>zéros</mark>

In [13]:
v=np.zeros(10 ,dtype=int)
print(v)

[0 0 0 0 0 0 0 0 0 0]


Création d'un tableau de 10 <mark>uns</mark>

In [14]:
v=np.ones(10, dtype=int)
print(v)

[1 1 1 1 1 1 1 1 1 1]


création d'un tableau rempli d'une même <mark>valeur donnée</mark>

In [15]:
# création d'un tableau de 10 valeurs, chacun égal à 5
v=np.full(10, 5)
print(v)

[5 5 5 5 5 5 5 5 5 5]


Création d'un tableau contenant une <mark>séquence</mark>, en définissant le début et la fin de la séquence

In [16]:
t=np.arange(2,10)
print(t)

[2 3 4 5 6 7 8 9]


Création d'un tableau contenant une séquence par <mark>pas</mark> donné

In [17]:
t=np.arange(1,10,2)
print(t)

[1 3 5 7 9]


Création d'un tableau rempli <mark>aléatoirement</mark>

In [18]:
# création d'un tableau de 8 éléments avec des entiers aléatoire de l'intervalle [0,9]
t=np.random.randint(10,size=8)
print(t)

[1 7 5 0 4 7 7 4]


<h2 style="color:blue">Acces a un élément d'un tableau</h2>

In [19]:
t=np.array([1,5,4,9,6,7])

# Pour accéder au premier élément
print(t[0])

1


In [20]:
t=np.array([1,5,4,9,6,7])

# Pour accéder au dernier élément
print(t[-1])

7


In [16]:
t=np.array([1,5,4,9,6,7])

# on peut aussi modifier un élément
t[2]=33
print(t)

[ 1  5 33  9  6  7]


<h2 style="color:blue">Acces à une séquence (Slicing)</h2>

In [20]:
T=np.arange(1,10)

# les élément de l'indice 1 à l'indice 4
x=T[1:5]
print(x)

[2 3 4 5]


In [21]:
T=np.arange(1,10)

# liste des elements de l'indice 1 à l'indice 4 par pas =2
x=T[1:5:2]
print(x)

[2 4]


In [22]:
T=np.arange(1,10)

# liste des elements de début du tableau jusqu'à l'élement d'indice 4
x=T[:5]
print(T)
print(x)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]


In [23]:
T=np.arange(1,10)

# liste des éléments de l'élément d'indice 5 jusqu'au dernier
x=T[5:]
print(T)
print(x)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [62]:
T=np.arange(1,10)

# Si le pas est négatif, le début et la fin du slice sont inversés. 
# On peut utiliser cette propriété pour inverser un tableau.
x=T[::-1]
print(T)
print(x)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


<h2 style="color:red">Opérations sur les tableaux Numpy</h2>

Jusqu'à maintenant dans ce chapitre, nous avons vu des choses très basiques sur les tableaux Numpy. A partir d'ici, nous allons voir ce qui rend Numpy vraiment indispensable.

<mark>Les boucles peuvent êtres lentes en Python</mark>

observez le temps d'exécution de ce morceau de code.


In [21]:
import numpy as np
def calcul_inverse(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
print(calcul_inverse(values))

tableau_large = np.random.randint(1, 100, size=1000000)

# Ceci est une facilité des notebooks jupyter pour 
# mesurer le temps d'exécution d'une instruction
%timeit calcul_inverse(tableau_large)


[0.33333333 1.         1.         0.5        0.33333333]
2.91 s ± 129 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Dans beaucoup de cas, Numpy fournit une interface pour ces opérations qui n'implique que des données du même type. Par exemple, on peut calculer les inverses de tous les éléments d'un tableau Numpy comme ceci.

In [24]:
%timeit (1.0 / tableau_large)

4.6 ms ± 250 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


L'opération a pris presque 1000 fois moins de temps.

À chaque fois que vous vous trouvez en train d'utiliser une boucle pour effectuer une opération en Python, demandez-vous si cette opération ne peut pas s'accomplir grâce à Numpy sans boucle.

Nous allons maintenant faire un tour d'horizon de ces opérations.

Les fonctions universelles


In [18]:
# Il y a tout d'abord des opération mathématiques simples
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # Division entière


x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


Vous pouvez aussi appeler des fonctions sur les tableaux Numpy, et même sur les listes Python.

In [6]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))


La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


Il y a plein d'autres fonctions, que je vous invite à découvrir dans la documentation de Numpy. La leçon à retenir ici est simple : évitez tant que possible les boucles.
Opérations Booléennes
Vous pouvez aussi exécuter des opérations booléennes sur vos tableaux. En clair, vous pouvez demander si une certaine condition est vraie pour chaque élément d'un tableau. Par exemple :


In [26]:
x = np.random.randint(10, size=10)
print(x)
x > 5


[6 3 2 9 3 6 7 0 8 6]


array([ True, False, False,  True, False,  True,  True, False,  True,
        True])

Vous pouvez coupler cette capacité avec la fonction  <mark>np.where</mark>, pour retourner parmi tous les éléments d'un tableau les index de ceux qui vérifient une certaine propriété :

In [26]:
x=np.arange(20)
print(x)
np.where(x > 10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


(array([11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)

<mark>Agrégation</mark>
Très souvent, face à de larges quantités de données, la première chose à faire est de calculer des statistiques sur nos données, comme la moyenne ou l'écart type. Numpy a des fonctions pour calculer ces données sur ses tableaux.


In [27]:
L = np.random.random(100)
np.sum(L)


49.96621561474166

Cette fonction existe aussi en Python, mais la version Numpy est beaucoup plus rapide. De même, Numpy a des équivalents pour  min  et  max. Faites cependant attention aux arguments optionnels de chaque version de ces fonctions. Gardez aussi à l'esprit que seule la version Numpy gère correctement les tableaux multidimensionnels.

In [10]:
%timeit sum(tableau_large)
%timeit np.sum(tableau_large)


257 ms ± 31.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
609 µs ± 24.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
